dist: xenial
sudo: required
services:
  - docker
language: go

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
  - go: "1.12.x"
    name: "Code Lint"
    script: make lint
  - go: "1.12.x"
    name: "Code UnitTest"
    script: make test
  - go: "1.12.x"
    name: "Code BuildRelease"
    script: make release

install:
  - make tools

branches:
  only:
    - master
